SELECT
    O.ORDERID, O.PRODUCTID, O.CURRENCY, O.QUANTITY, O.SHIPPINGCOST, O.AMOUNT, O.CHANNEL, O.CHANNELGROUP, CASE WHEN O.CAMPAIGN = '""' THEN NULL ELSE  O.CAMPAIGN END AS CAMPAIGN , O.DATETIME, O.CREATED_AT, O.HARDID,
    (O.QUANTITY*O.AMOUNT)+O.SHIPPINGCOST AS TOTAL_AMOUNT,
    I.NAME,
    I.CATEGORY
FROM
    {{ ref('src_order') }} O
    LEFT JOIN  {{ ref('src_inventory') }} I ON O.PRODUCTID = I.PRODUCTID